version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=chatapp
    restart: always
    networks:
      - chat-network

  chat-backend:
    build:
      context: ./chat-backend
      dockerfile: Dockerfile
    deploy:
      replicas: 4
    restart: always
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=chatapp
    networks:
      - chat-network

  nginx-backend:
    image: nginx:1.21-alpine
    container_name: nginx-backend
    volumes:
      - ./nginx/backend.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "88:88"
    depends_on:
      - chat-backend
    restart: always
    networks:
      - chat-network

  chat-frontend:
    build:
      context: ./chat-frontend
      dockerfile: Dockerfile
    container_name: chat-frontend
    restart: always
    depends_on:
      - nginx-backend
    ports:
      - "90:90"
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local 